//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.19 at 09:01:20 PM NZST 
//


package Log;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="cost" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="weightcost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                     &lt;element name="volumecost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                     &lt;element name="maxWeight" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                     &lt;element name="maxVolume" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                     &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                     &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                     &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="price" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="weightcost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                     &lt;element name="volumecost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="mail" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                     &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                     &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="timelimit">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="maxDeliveryTime" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="discontinue">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "costOrPriceOrMail"
})
@XmlRootElement(name = "Log")
public class Log {

    @XmlElements({
        @XmlElement(name = "mail", type = Log.Mail.class),
        @XmlElement(name = "cost", type = Log.Cost.class),
        @XmlElement(name = "discontinue", type = Log.Discontinue.class),
        @XmlElement(name = "price", type = Log.Price.class),
        @XmlElement(name = "timelimit", type = Log.Timelimit.class)
    })
    protected List<Object> costOrPriceOrMail;

    /**
     * Gets the value of the costOrPriceOrMail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the costOrPriceOrMail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCostOrPriceOrMail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Log.Mail }
     * {@link Log.Cost }
     * {@link Log.Discontinue }
     * {@link Log.Price }
     * {@link Log.Timelimit }
     * 
     * 
     */
    public List<Object> getCostOrPriceOrMail() {
        if (costOrPriceOrMail == null) {
            costOrPriceOrMail = new ArrayList<Object>();
        }
        return this.costOrPriceOrMail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weightcost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="volumecost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="maxWeight" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="maxVolume" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "company",
        "to",
        "from",
        "type",
        "weightcost",
        "volumecost",
        "maxWeight",
        "maxVolume",
        "duration",
        "frequency",
        "day"
    })
    public static class Cost {

        @XmlElement(required = true)
        protected String company;
        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String from;
        @XmlElement(required = true)
        protected String type;
        @XmlSchemaType(name = "unsignedByte")
        protected short weightcost;
        @XmlSchemaType(name = "unsignedByte")
        protected short volumecost;
        @XmlSchemaType(name = "unsignedShort")
        protected int maxWeight;
        @XmlSchemaType(name = "unsignedShort")
        protected int maxVolume;
        @XmlSchemaType(name = "unsignedByte")
        protected short duration;
        @XmlSchemaType(name = "unsignedByte")
        protected short frequency;
        @XmlElement(required = true)
        protected String day;

        /**
         * Gets the value of the company property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompany() {
            return company;
        }

        /**
         * Sets the value of the company property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompany(String value) {
            this.company = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the weightcost property.
         * 
         */
        public short getWeightcost() {
            return weightcost;
        }

        /**
         * Sets the value of the weightcost property.
         * 
         */
        public void setWeightcost(short value) {
            this.weightcost = value;
        }

        /**
         * Gets the value of the volumecost property.
         * 
         */
        public short getVolumecost() {
            return volumecost;
        }

        /**
         * Sets the value of the volumecost property.
         * 
         */
        public void setVolumecost(short value) {
            this.volumecost = value;
        }

        /**
         * Gets the value of the maxWeight property.
         * 
         */
        public int getMaxWeight() {
            return maxWeight;
        }

        /**
         * Sets the value of the maxWeight property.
         * 
         */
        public void setMaxWeight(int value) {
            this.maxWeight = value;
        }

        /**
         * Gets the value of the maxVolume property.
         * 
         */
        public int getMaxVolume() {
            return maxVolume;
        }

        /**
         * Sets the value of the maxVolume property.
         * 
         */
        public void setMaxVolume(int value) {
            this.maxVolume = value;
        }

        /**
         * Gets the value of the duration property.
         * 
         */
        public short getDuration() {
            return duration;
        }

        /**
         * Sets the value of the duration property.
         * 
         */
        public void setDuration(short value) {
            this.duration = value;
        }

        /**
         * Gets the value of the frequency property.
         * 
         */
        public short getFrequency() {
            return frequency;
        }

        /**
         * Sets the value of the frequency property.
         * 
         */
        public void setFrequency(short value) {
            this.frequency = value;
        }

        /**
         * Gets the value of the day property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDay() {
            return day;
        }

        /**
         * Sets the value of the day property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDay(String value) {
            this.day = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "company",
        "to",
        "from",
        "type"
    })
    public static class Discontinue {

        @XmlElement(required = true)
        protected String company;
        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String from;
        @XmlElement(required = true)
        protected String type;

        /**
         * Gets the value of the company property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompany() {
            return company;
        }

        /**
         * Sets the value of the company property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompany(String value) {
            this.company = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "day",
        "to",
        "from",
        "weight",
        "volume",
        "priority"
    })
    public static class Mail {

        @XmlElement(required = true)
        protected String day;
        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String from;
        @XmlSchemaType(name = "unsignedShort")
        protected int weight;
        @XmlSchemaType(name = "unsignedByte")
        protected short volume;
        @XmlElement(required = true)
        protected String priority;

        /**
         * Gets the value of the day property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDay() {
            return day;
        }

        /**
         * Sets the value of the day property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDay(String value) {
            this.day = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         */
        public int getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         */
        public void setWeight(int value) {
            this.weight = value;
        }

        /**
         * Gets the value of the volume property.
         * 
         */
        public short getVolume() {
            return volume;
        }

        /**
         * Sets the value of the volume property.
         * 
         */
        public void setVolume(short value) {
            this.volume = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weightcost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="volumecost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "to",
        "from",
        "priority",
        "weightcost",
        "volumecost"
    })
    public static class Price {

        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String from;
        @XmlElement(required = true)
        protected String priority;
        @XmlSchemaType(name = "unsignedByte")
        protected short weightcost;
        @XmlSchemaType(name = "unsignedByte")
        protected short volumecost;

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }

        /**
         * Gets the value of the weightcost property.
         * 
         */
        public short getWeightcost() {
            return weightcost;
        }

        /**
         * Sets the value of the weightcost property.
         * 
         */
        public void setWeightcost(short value) {
            this.weightcost = value;
        }

        /**
         * Gets the value of the volumecost property.
         * 
         */
        public short getVolumecost() {
            return volumecost;
        }

        /**
         * Sets the value of the volumecost property.
         * 
         */
        public void setVolumecost(short value) {
            this.volumecost = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="maxDeliveryTime" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "to",
        "from",
        "priority",
        "maxDeliveryTime"
    })
    public static class Timelimit {

        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String from;
        @XmlElement(required = true)
        protected String priority;
        @XmlSchemaType(name = "unsignedByte")
        protected short maxDeliveryTime;

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }

        /**
         * Gets the value of the maxDeliveryTime property.
         * 
         */
        public short getMaxDeliveryTime() {
            return maxDeliveryTime;
        }

        /**
         * Sets the value of the maxDeliveryTime property.
         * 
         */
        public void setMaxDeliveryTime(short value) {
            this.maxDeliveryTime = value;
        }

    }

}
