//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.13 at 09:39:33 PM NZST 
//


package Log;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="cost" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                     &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                     &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="price" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="weightcost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                     &lt;element name="volumecost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="route" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                     &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="maxWeight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="maxVolume" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                     &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="costWeight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="costVolume" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="mail" maxOccurs="unbounded">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                     &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                     &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                     &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                     &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="timelimit">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="maxDeliveryTime" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="discontinue">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "costOrPriceOrRoute"
})
@XmlRootElement(name = "Log")
public class Log {

    @XmlElements({
        @XmlElement(name = "timelimit", type = Log.Timelimit.class),
        @XmlElement(name = "discontinue", type = Log.Discontinue.class),
        @XmlElement(name = "cost", type = Log.Cost.class),
        @XmlElement(name = "mail", type = Log.Mail.class),
        @XmlElement(name = "price", type = Log.Price.class),
        @XmlElement(name = "route", type = Log.Route.class)
    })
    protected List<Object> costOrPriceOrRoute;

    /**
     * Gets the value of the costOrPriceOrRoute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the costOrPriceOrRoute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCostOrPriceOrRoute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Log.Timelimit }
     * {@link Log.Discontinue }
     * {@link Log.Cost }
     * {@link Log.Mail }
     * {@link Log.Price }
     * {@link Log.Route }
     * 
     * 
     */
    public List<Object> getCostOrPriceOrRoute() {
        if (costOrPriceOrRoute == null) {
            costOrPriceOrRoute = new ArrayList<Object>();
        }
        return this.costOrPriceOrRoute;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "priority",
        "destination",
        "origin",
        "id",
        "weight",
        "volume"
    })
    public static class Cost {

        @XmlElement(required = true)
        protected int priority;
        @XmlElement(required = true)
        protected String destination;
        @XmlElement(required = true)
        protected String origin;
        @XmlElement(required = true)
        protected int id;
        protected double weight;
        protected double volume;

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPriority(int value) {
            this.priority = value;
        }

        /**
         * Gets the value of the destination property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestination() {
            return destination;
        }

        /**
         * Sets the value of the destination property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestination(String value) {
            this.destination = value;
        }

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         */
        public double getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         */
        public void setWeight(double value) {
            this.weight = value;
        }

        /**
         * Gets the value of the volume property.
         * 
         */
        public double getVolume() {
            return volume;
        }

        /**
         * Sets the value of the volume property.
         * 
         */
        public void setVolume(double value) {
            this.volume = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "company",
        "to",
        "from",
        "type"
    })
    public static class Discontinue {

        @XmlElement(required = true)
        protected String company;
        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String from;
        @XmlElement(required = true)
        protected String type;

        /**
         * Gets the value of the company property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompany() {
            return company;
        }

        /**
         * Sets the value of the company property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompany(String value) {
            this.company = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="volume" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="cost" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "destination",
        "origin",
        "weight",
        "volume",
        "priority",
        "date",
        "income",
        "cost",
        "name",
        "time"
    })
    public static class Mail {

        @XmlElement(required = true)
        protected int id;
        @XmlElement(required = true)
        protected String destination;
        @XmlElement(required = true)
        protected String origin;
        protected double weight;
        protected double volume;
        @XmlElement(required = true)
        protected int priority;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected Date date;
        protected double income;
        protected double cost;
        @XmlElement(required = true)
        protected String name;
        protected double time;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the destination property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestination() {
            return destination;
        }

        /**
         * Sets the value of the destination property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestination(String value) {
            this.destination = value;
        }

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         */
        public double getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         */
        public void setWeight(double value) {
            this.weight = value;
        }

        /**
         * Gets the value of the volume property.
         * 
         */
        public double getVolume() {
            return volume;
        }

        /**
         * Sets the value of the volume property.
         * 
         */
        public void setVolume(double value) {
            this.volume = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPriority(int value) {
            this.priority = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public Date getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(Date value) {
            this.date = value;
        }

        /**
         * Gets the value of the income property.
         * 
         */
        public double getIncome() {
            return income;
        }

        /**
         * Sets the value of the income property.
         * 
         */
        public void setIncome(double value) {
            this.income = value;
        }

        /**
         * Gets the value of the cost property.
         * 
         */
        public double getCost() {
            return cost;
        }

        /**
         * Sets the value of the cost property.
         * 
         */
        public void setCost(double value) {
            this.cost = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the time property.
         * 
         */
        public double getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         */
        public void setTime(double value) {
            this.time = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="weightcost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="volumecost" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "to",
        "from",
        "priority",
        "weightcost",
        "volumecost"
    })
    public static class Price {

        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String from;
        @XmlElement(required = true)
        protected String priority;
        @XmlSchemaType(name = "unsignedByte")
        protected short weightcost;
        @XmlSchemaType(name = "unsignedByte")
        protected short volumecost;

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }

        /**
         * Gets the value of the weightcost property.
         * 
         */
        public short getWeightcost() {
            return weightcost;
        }

        /**
         * Sets the value of the weightcost property.
         * 
         */
        public void setWeightcost(short value) {
            this.weightcost = value;
        }

        /**
         * Gets the value of the volumecost property.
         * 
         */
        public short getVolumecost() {
            return volumecost;
        }

        /**
         * Sets the value of the volumecost property.
         * 
         */
        public void setVolumecost(short value) {
            this.volumecost = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="maxWeight" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="maxVolume" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="day" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="frequency" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="companyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="costWeight" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="costVolume" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "destination",
        "origin",
        "maxWeight",
        "maxVolume",
        "priority",
        "day",
        "frequency",
        "duration",
        "companyName",
        "costWeight",
        "costVolume"
    })
    public static class Route {

        @XmlElement(required = true)
        protected int id;
        @XmlElement(required = true)
        protected String destination;
        @XmlElement(required = true)
        protected String origin;
        protected double maxWeight;
        protected double maxVolume;
        @XmlElement(required = true)
        protected int priority;
        @XmlElement(required = true)
        protected String day;
        protected double frequency;
        protected double duration;
        @XmlElement(required = true)
        protected String companyName;
        protected double costWeight;
        protected double costVolume;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the destination property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestination() {
            return destination;
        }

        /**
         * Sets the value of the destination property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestination(String value) {
            this.destination = value;
        }

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

        /**
         * Gets the value of the maxWeight property.
         * 
         */
        public double getMaxWeight() {
            return maxWeight;
        }

        /**
         * Sets the value of the maxWeight property.
         * 
         */
        public void setMaxWeight(double value) {
            this.maxWeight = value;
        }

        /**
         * Gets the value of the maxVolume property.
         * 
         */
        public double getMaxVolume() {
            return maxVolume;
        }

        /**
         * Sets the value of the maxVolume property.
         * 
         */
        public void setMaxVolume(double value) {
            this.maxVolume = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public int getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPriority(int value) {
            this.priority = value;
        }

        /**
         * Gets the value of the day property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDay() {
            return day;
        }

        /**
         * Sets the value of the day property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDay(String value) {
            this.day = value;
        }

        /**
         * Gets the value of the frequency property.
         * 
         */
        public double getFrequency() {
            return frequency;
        }

        /**
         * Sets the value of the frequency property.
         * 
         */
        public void setFrequency(double value) {
            this.frequency = value;
        }

        /**
         * Gets the value of the duration property.
         * 
         */
        public double getDuration() {
            return duration;
        }

        /**
         * Sets the value of the duration property.
         * 
         */
        public void setDuration(double value) {
            this.duration = value;
        }

        /**
         * Gets the value of the companyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyName() {
            return companyName;
        }

        /**
         * Sets the value of the companyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyName(String value) {
            this.companyName = value;
        }

        /**
         * Gets the value of the costWeight property.
         * 
         */
        public double getCostWeight() {
            return costWeight;
        }

        /**
         * Sets the value of the costWeight property.
         * 
         */
        public void setCostWeight(double value) {
            this.costWeight = value;
        }

        /**
         * Gets the value of the costVolume property.
         * 
         */
        public double getCostVolume() {
            return costVolume;
        }

        /**
         * Sets the value of the costVolume property.
         * 
         */
        public void setCostVolume(double value) {
            this.costVolume = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="to" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="maxDeliveryTime" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "to",
        "from",
        "priority",
        "maxDeliveryTime"
    })
    public static class Timelimit {

        @XmlElement(required = true)
        protected String to;
        @XmlElement(required = true)
        protected String from;
        @XmlElement(required = true)
        protected String priority;
        @XmlSchemaType(name = "unsignedByte")
        protected short maxDeliveryTime;

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTo(String value) {
            this.to = value;
        }

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrom(String value) {
            this.from = value;
        }

        /**
         * Gets the value of the priority property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPriority(String value) {
            this.priority = value;
        }

        /**
         * Gets the value of the maxDeliveryTime property.
         * 
         */
        public short getMaxDeliveryTime() {
            return maxDeliveryTime;
        }

        /**
         * Sets the value of the maxDeliveryTime property.
         * 
         */
        public void setMaxDeliveryTime(short value) {
            this.maxDeliveryTime = value;
        }

    }

}
