//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.19 at 09:01:20 PM NZST 
//


package Log;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Log package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Log
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Log.Discontinue }
     * 
     */
    public Log.Discontinue createLogDiscontinue() {
        return new Log.Discontinue();
    }

    /**
     * Create an instance of {@link Log.Cost }
     * 
     */
    public Log.Cost createLogCost() {
        return new Log.Cost();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link Log.Timelimit }
     * 
     */
    public Log.Timelimit createLogTimelimit() {
        return new Log.Timelimit();
    }

    /**
     * Create an instance of {@link Log.Price }
     * 
     */
    public Log.Price createLogPrice() {
        return new Log.Price();
    }

    /**
     * Create an instance of {@link Log.Mail }
     * 
     */
    public Log.Mail createLogMail() {
        return new Log.Mail();
    }

}
