//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.16 at 10:27:25 PM NZST 
//


package Log;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Log package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Log
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Log.Mail }
     * 
     */
    public Log.Mail createLogMail() {
        return new Log.Mail();
    }

    /**
     * Create an instance of {@link Log.KPEvents.Event.Routes.Route }
     * 
     */
    public Log.KPEvents.Event.Routes.Route createLogKPEventsEventRoutesRoute() {
        return new Log.KPEvents.Event.Routes.Route();
    }

    /**
     * Create an instance of {@link Log.KPEvents.Event.Cost }
     * 
     */
    public Log.KPEvents.Event.Cost createLogKPEventsEventCost() {
        return new Log.KPEvents.Event.Cost();
    }

    /**
     * Create an instance of {@link Log.Route }
     * 
     */
    public Log.Route createLogRoute() {
        return new Log.Route();
    }

    /**
     * Create an instance of {@link Log.KPEvents.Event.Route }
     * 
     */
    public Log.KPEvents.Event.Route createLogKPEventsEventRoute() {
        return new Log.KPEvents.Event.Route();
    }

    /**
     * Create an instance of {@link Log.KPEvents.Event.Mail }
     * 
     */
    public Log.KPEvents.Event.Mail createLogKPEventsEventMail() {
        return new Log.KPEvents.Event.Mail();
    }

    /**
     * Create an instance of {@link Log.KPEvents.Event.Routes }
     * 
     */
    public Log.KPEvents.Event.Routes createLogKPEventsEventRoutes() {
        return new Log.KPEvents.Event.Routes();
    }

    /**
     * Create an instance of {@link Log.KPEvents.Event.Mails }
     * 
     */
    public Log.KPEvents.Event.Mails createLogKPEventsEventMails() {
        return new Log.KPEvents.Event.Mails();
    }

    /**
     * Create an instance of {@link Log.Timelimit }
     * 
     */
    public Log.Timelimit createLogTimelimit() {
        return new Log.Timelimit();
    }

    /**
     * Create an instance of {@link Log.KPEvents }
     * 
     */
    public Log.KPEvents createLogKPEvents() {
        return new Log.KPEvents();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link Log.Cost }
     * 
     */
    public Log.Cost createLogCost() {
        return new Log.Cost();
    }

    /**
     * Create an instance of {@link Log.Price }
     * 
     */
    public Log.Price createLogPrice() {
        return new Log.Price();
    }

    /**
     * Create an instance of {@link Log.KPEvents.Event }
     * 
     */
    public Log.KPEvents.Event createLogKPEventsEvent() {
        return new Log.KPEvents.Event();
    }

    /**
     * Create an instance of {@link Log.Discontinue }
     * 
     */
    public Log.Discontinue createLogDiscontinue() {
        return new Log.Discontinue();
    }

    /**
     * Create an instance of {@link Log.KPEvents.Event.Mails.Mail }
     * 
     */
    public Log.KPEvents.Event.Mails.Mail createLogKPEventsEventMailsMail() {
        return new Log.KPEvents.Event.Mails.Mail();
    }

}
